# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: postgres
  user: blog_user
  password: blog_password
  port: 5432
  database: blog_dev

production:
  <<: *default
  user:
  password:
  port: 5432
  database: blog_prod
